# Example docker-compose.yml
version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword